name: fcm
description: TwakeMail FCM extension
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  ### Dependencies from git ###
  # TODO: We will change it when the PR in upstream repository will be merged
  # https://github.com/linagora/jmap-dart-client/pull/87
  jmap_dart_client:
    git:
      url: https://github.com/linagora/jmap-dart-client.git
      ref: sprint25_from_migrate_5jun

  ### Dependencies from pub.dev ###
  equatable: 2.0.5

  json_annotation: 4.8.0

  dio: 5.0.0

  http_mock_adapter: 0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.1

  build_runner: 2.3.3

  json_serializable: 6.6.1

  mockito: 5.4.4

dependency_overrides:
  build_runner: 2.4.12
  build_runner_core: 7.2.9
  json_annotation: 4.8.1

flutter:
  uses-material-design: true