name: tmail_ui_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter # 2.5.3

  flutter_localizations:
    sdk: flutter

  core:
    path: core

  model:
    path: model

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  # GetX
  get: 4.3.8

  # intl
  intl_generator: 0.2.0+0

  # flutter_svg
  flutter_svg: 0.23.0+1

  # Http client
  dio: 4.0.0

  # equatable
  equatable: 2.0.3

  # shared_preferences
  shared_preferences: 2.0.5

  # either
  dartz: 0.10.0-nullsafety.2

  # flutter_typeahead
  flutter_typeahead: 3.1.1

  built_collection: 5.1.0

  # jmap_dart_client
  jmap_dart_client:
    git:
      url: git://github.com/linagora/jmap-dart-client.git
      ref: master

  # http_parser
  http_parser: 4.0.0

  collection: 1.15.0

  # file_size
  filesize: 2.0.1

  # flutter_chips_input
  flutter_chips_input:
    git:
      url: git://github.com/dab246/flutter_chips_input.git
      ref: master

  # uuid
  uuid: 3.0.4

  # flutter_downloader
  flutter_downloader: 1.7.0

  # external_path
  external_path: 1.0.1

  # path_provider
  path_provider: 2.0.3

  # device_info
  device_info: 2.0.2

  # permission_handler
  permission_handler: 8.1.6

  # share
  share: 2.0.4

  # flutter_contacts
  contacts_service:
    git:
      url: git://github.com/linagora/flutter_contacts.git
      ref: master

  # file_picker
  file_picker: 3.0.2+2

  # hive
  hive: 2.0.4

  # enough_html_editor
  enough_html_editor:
    git:
      url: git://github.com/dab246/enough_html_editor.git
      ref: fix_bug_enough_platform_widgets

dependency_overrides:
  # From what could find on the web, it seems some lib is using flutter_colorpicker to 0.4.0
  # which conflicts with flutter sdk 2.5.3. Will see when upgradings libs if it's still present
  flutter_colorpicker: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.0.5

  test: 1.17.10

  mockito: 5.0.10

  hive_generator: 1.1.1
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: CircularStd
      fonts:
        - asset: assets/fonts/CircularStd/CircularStd-Bold.otf
          weight: 700
        - asset: assets/fonts/CircularStd/CircularStd-Medium.otf
          weight: 500
        - asset: assets/fonts/CircularStd/CircularStd-Book.otf