name: tmail_ui_user
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.14.6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  core:
    path: core

  model:
    path: model

  contact:
    path: contact

  rule_filter:
    path: rule_filter

  forward:
    path: forward

  fcm:
    path: fcm

  email_recovery:
    path: email_recovery

  server_settings:
    path: server_settings

  ### Dependencies from git ###
  rich_text_composer:
    git:
      url: https://github.com/linagora/rich-text-composer.git
      ref: main

  html_editor_enhanced:
    git:
      url: https://github.com/linagora/html-editor-enhanced.git
      ref: main

  jmap_dart_client:
    git:
      url: https://github.com/linagora/jmap-dart-client.git
      ref: main

  contacts_service:
    git:
      url: https://github.com/linagora/flutter_contacts.git
      ref: master

  receive_sharing_intent:
    git:
      url: https://github.com/linagora/receive_sharing_intent.git
      ref: main

  flutter_appauth_web:
    git:
      url: https://github.com/CarlosPacheco/flutter_appauth_web.git
      ref: main

  flutter_date_range_picker:
    git:
      url: https://github.com/linagora/flutter-date-range-picker.git
      ref: main
  # TODO: Move back to master after sprint 25 released

  super_tag_editor: 0.3.0

  # TODO: We will change it when the PR in upstream repository will be merged
  # https://github.com/dietfriends/dns_client/pull/9
  dns_client:
    git:
      url: https://github.com/linagora/dns_client.git
      ref: twake-supported

  # TODO: We will change it when the PR in upstream repository will be merged
  # https://github.com/espresso3389/flutter_pdf_render/pull/148
  pdf_render:
    git:
      url: https://github.com/linagora/flutter_pdf_render.git
      ref: main

  linagora_design_flutter:
    git:
      url: https://github.com/linagora/linagora-design-flutter.git
      ref: master

  ### Dependencies from pub.dev ###
  cupertino_icons: 1.0.6

  get: 4.6.6

  intl_generator: 0.4.1

  flutter_svg: 2.0.9

  dio: 5.0.0

  equatable: 2.0.5

  shared_preferences: 2.0.18

  dartz: 0.10.1

  flutter_dotenv: 5.0.2

  built_collection: 5.1.1

  textfield_tags: 2.0.2

  http_parser: 4.0.2

  collection: 1.18.0

  filesize: 2.0.1

  uuid: 3.0.7

  flutter_downloader: 1.10.2

  external_path: 1.0.3

  path_provider: 2.1.1

  device_info_plus: 8.1.0

  permission_handler: 10.2.0

  share_plus: 7.2.1

  hive: 2.2.3

  pointer_interceptor: 0.10.1

  rxdart: 0.27.7

  connectivity_plus: 3.0.3

  dropdown_button2: 2.0.0

  flutter_staggered_grid_view: 0.6.2

  flutter_portal: 1.1.3

  timeago: 3.7.0

  better_open_file: 3.6.4

  flutter_appauth: 6.0.6

  percent_indicator: 4.2.2

  worker_manager: 5.0.3

  async: 2.11.0

  html: 0.15.3

  custom_pop_up_menu: 1.2.4

  byte_converter: 1.3.0

  json_annotation: 4.8.0

  url_launcher: 6.1.10

  firebase_core: 2.7.0

  firebase_messaging: 14.2.5

  flutter_local_notifications: 16.2.0

  fading_edge_scrollview: 4.1.1

  focused_menu_custom: 1.2.0

  focus_detector_v2: 3.0.0+2

  universal_html: 2.2.4

  debounce_throttle: 2.0.0

  flutter_appauth_platform_interface: 6.0.0

  intl: 0.19.0

  external_app_launcher: 3.1.0

  workmanager: 0.5.1

  flutter_typeahead: 5.0.2

  flutter_keyboard_visibility: 6.0.0

  extended_text: 13.0.2

  date_format: 2.0.7

  flutter_linkify: 6.0.0

  flutter_slidable: 3.1.0

  url_strategy: 0.2.0

  dotted_border: 2.1.0

  internet_connection_checker: 1.0.0+1

  flutter_image_compress: 2.1.0

  back_button_interceptor: 7.0.0

  flutter_secure_storage: 8.0.0

  mime: 1.0.4

  desktop_drop: 0.4.4

  future_loading_dialog: 0.3.0

  file_picker: 5.3.1

  app_settings: 5.1.1

  web_socket_channel: 2.4.3

  tip_dialog: 4.0.0

  flutter_web_auth_2: 3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.3.3

  mockito: 5.4.4

  hive_generator: 2.0.0

  flutter_lints: 2.0.1

  flutter_native_splash: 2.2.18

  flutter_launcher_icons: 0.12.0

  xml: 6.3.0

  json_serializable: 6.6.1

  http_mock_adapter: 0.4.2

  patrol: 3.11.1

  plugin_platform_interface: 2.1.8

dependency_overrides:
  firebase_core_platform_interface: 4.6.0

  # TODO: replace when upstream PR is merged:
  # https://github.com/miguelpruivo/flutter_file_picker/pull/1482
  file_picker:
    git:
      url: https://github.com/linagora/flutter_file_picker
      ref: email_supported_5.3.1

  json_annotation: 4.8.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/icons/
    - env.file
    - configurations/
    - configurations/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-Regular.ttf

flutter_icons:
  android: true
  ios: false
  remove_alpha_ios: true
  image_path: "assets/icons/icon_launcher.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/icon_launcher.png"

flutter_native_splash:
  color: "#000000"
  branding: "assets/icons/icon_branding.png"
  image: "assets/icons/icon_logo.png"

cider:
  link_template:
    tag: https://github.com/linagora/tmail-flutter/releases/tag/v%tag% # initial release link template

patrol:
  app_name: Twake Mail
  android:
    package_name: com.linagora.android.teammail
