name: cozy
description: "Cozy integration module"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  ### TODO: Revert back to master when https://github.com/linagora/linagora-design-flutter/pull/67 is merged
  linagora_design_flutter:
    git:
      url: https://github.com/linagora/linagora-design-flutter.git
      ref: feature/web-link-generator

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
